In [1]:
import numpy as np

In [56]:
A=np.array([1,4,6,7j])
# sorted(A)


[7j, (1+0j), (4+0j), (6+0j)]

In [6]:
print(A[2])

(6+0j)


In [7]:
print(A)

[1.+0.j 4.+0.j 6.+0.j 0.+7.j]


In [8]:
B=np.array([1,2,3,4.5,6.1])

In [9]:
B

array([1. , 2. , 3. , 4.5, 6.1])

In [10]:
A.shape

(4,)

In [2]:
B=np.array([[1,2,3],[4,5,6]])

In [3]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
B.shape

(2, 3)

In [5]:
C=np.array([[7,8,9],[4,5,6],[1,2,3]])

In [6]:
C.shape

(3, 3)

In [7]:
B+C

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [17]:
B-C

array([[-6, -6, -6],
       [ 0,  0,  0],
       [ 6,  6,  6]])

In [9]:
B**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [20]:
D=np.array([[1,2],[3,4],[4,5]])

In [21]:
C.shape

(3, 3)

In [22]:
D.shape

(3, 2)

In [23]:
C.dot(D)
# dot product of c with d

array([[67, 91],
       [43, 58],
       [19, 25]])

In [24]:
A=np.array([1,2,3])
B=np.array([2,3,4])

In [25]:
np.add(A,B)

array([3, 5, 7])

In [26]:
np.subtract(A,B)

array([-1, -1, -1])

In [27]:
np.multiply(A,B)

array([ 2,  6, 12])

In [28]:
np.divide(A,B)

array([0.5       , 0.66666667, 0.75      ])

In [29]:
C=np.array([4,5,8])
np.mod(C,B)
# remainder

array([0, 2, 0], dtype=int32)

In [30]:
A=np.array([1,2,3,4j,6+3j])

In [31]:
A

array([1.+0.j, 2.+0.j, 3.+0.j, 0.+4.j, 6.+3.j])

In [32]:
np.real(A)

array([1., 2., 3., 0., 6.])

In [33]:
np.imag(A)

array([0., 0., 0., 4., 3.])

In [34]:
np.conj(A)

array([1.-0.j, 2.-0.j, 3.-0.j, 0.-4.j, 6.-3.j])

In [35]:
np.angle(A)

array([0.        , 0.        , 0.        , 1.57079633, 0.46364761])

In [36]:
np.power(B,2)

array([ 4,  9, 16], dtype=int32)

In [37]:
np.random.random((2,3))

array([[0.13406604, 0.29513056, 0.62316768],
       [0.6776641 , 0.82461443, 0.45580437]])

In [38]:
np.sum(B)

9

In [39]:
np.min(B)

2

In [40]:
np.max(B)

4

In [42]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
A=np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
np.sqrt(B)

array([1.41421356, 1.73205081, 2.        ])

In [61]:
print(A)
print(A.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [50]:
print(A)
print(A.flat)
print(A.flat[5])
print(A.flatten())
# convert to single dimension

[[0 1 2]
 [3 4 5]
 [6 7 8]]
5
[0 1 2 3 4 5 6 7 8]


In [51]:
A.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [53]:
A=np.matrix('[1,2;3,4;7,8]')
print(A)
# of equal row and column

[[1 2]
 [3 4]
 [7 8]]


In [80]:
B=np.matrix('[1,2,3;5,6,7]')
print(B)

[[1 2 3]
 [5 6 7]]


In [82]:
A*B

matrix([[11, 14, 17],
        [23, 30, 37]])

In [83]:
A.T

matrix([[1, 3],
        [2, 4]])

In [84]:
A.I
# prints the inverse

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [87]:
A + A.T
# operation broadcasting

matrix([[2, 5],
        [5, 8]])

## Lab 8
1. WAP using numpy input two arrays as A=(1,0) and B=(0,1) and calcuate two new arrays as
    C = 1/sqrt(2)(A+B)
    D = 1/sqrt(2)(A+B)
2. WAP using numpy to create a matrix A of 2x2 then find the size of A and print element (1,1) of A
3. WAP using numpy to find an element in an array
4. WAP using numpy to sort an array4
5. WAP using numpy to sort a 2D array
6. WAP using numpy to add elements of diagnols
7. WAP using numpy to add elements of diagnols and find which one is greater

In [58]:
A = np.array([[1,2,3],[4,5,6]])

In [60]:
A.shape

(2, 3)

In [61]:
A.ndim


2

In [63]:
A.size
# shape mulitplied

6

In [64]:
len(A)

2

In [65]:
A[0,1]

2

In [66]:
A[:,1]

array([2, 5])

In [67]:
A[1,:]

array([4, 5, 6])

In [68]:
A[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
np.zeros([3,4])+6

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [74]:
np.ones([3,4])*8

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [75]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
A.mean()

3.5

In [77]:
A.std()

1.707825127659933

In [78]:
A.min()

1

In [79]:
A.max()

6

In [80]:
A.argsort()

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [81]:
A = np.array([1,5,2,8,10,22])

In [90]:
A.argsort()

array([0, 2, 1, 3, 4, 5], dtype=int64)

In [91]:
np.pi

3.141592653589793

In [92]:
A

array([ 1,  5,  2,  8, 10, 22])

In [93]:
np.sin(A)

array([ 0.84147098, -0.95892427,  0.90929743,  0.98935825, -0.54402111,
       -0.00885131])

In [94]:
np.linspace(-5,5,11)

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [95]:
np.linspace(-np.pi,np.pi,100)

array([-3.14159265, -3.07812614, -3.01465962, -2.9511931 , -2.88772658,
       -2.82426006, -2.76079354, -2.69732703, -2.63386051, -2.57039399,
       -2.50692747, -2.44346095, -2.37999443, -2.31652792, -2.2530614 ,
       -2.18959488, -2.12612836, -2.06266184, -1.99919533, -1.93572881,
       -1.87226229, -1.80879577, -1.74532925, -1.68186273, -1.61839622,
       -1.5549297 , -1.49146318, -1.42799666, -1.36453014, -1.30106362,
       -1.23759711, -1.17413059, -1.11066407, -1.04719755, -0.98373103,
       -0.92026451, -0.856798  , -0.79333148, -0.72986496, -0.66639844,
       -0.60293192, -0.53946541, -0.47599889, -0.41253237, -0.34906585,
       -0.28559933, -0.22213281, -0.1586663 , -0.09519978, -0.03173326,
        0.03173326,  0.09519978,  0.1586663 ,  0.22213281,  0.28559933,
        0.34906585,  0.41253237,  0.47599889,  0.53946541,  0.60293192,
        0.66639844,  0.72986496,  0.79333148,  0.856798  ,  0.92026451,
        0.98373103,  1.04719755,  1.11066407,  1.17413059,  1.23

In [98]:
A = np.array([[1,2,3],[4,5,6]])
A[1,:].sum()

15

In [100]:
A[:,2].sum()

9

In [101]:
x = np.array([0.5])

# Bins - 5 bins in total
bins = np.array([0,1,2,3])

# Digitize function - 0.5 belong to the bin 0<= 0.5 <1 - therefore returned index 1
np.digitize(x,bins)
# array([1], dtype=int64)

# The input array can contain several inputs
x = np.array([-0.5,1,3.5])

# Digitize function
np.digitize(x,bins)
# array([0, 2, 4], dtype=int64)

array([0, 2, 4], dtype=int64)

In [102]:
# repeat number 3 5 times
np.repeat(3,5)
# array([3, 3, 3, 3, 3])

# repeat string '2015' 5 times
np.repeat('2015',5)
# array(['2015', '2015', '2015', '2015', '2015'], dtype='<U4')

array(['2015', '2015', '2015', '2015', '2015'], dtype='<U4')

In [103]:
# repeat number 3 5 times
np.repeat(3,5)
# array([3, 3, 3, 3, 3])

# repeat string '2015' 5 times
np.repeat('2015',5)
# array(['2015', '2015', '2015', '2015', '2015'], dtype='<U4')

array(['2015', '2015', '2015', '2015', '2015'], dtype='<U4')

In [107]:
import pandas as pd
# sales 2017
sales_2017 = pd.DataFrame([['chair',20],['sofa',24],['table',15]],columns=['product','sales_units'])

# sales 2018
sales_2018 = pd.DataFrame([['chair',25],['sofa',10],['shelf',10]],columns=['product','sales_units'])

# add year column in data frame 2017
sales_2017['year'] = np.repeat(2017,sales_2017.shape[0])

# add year column in data frame 2018
sales_2018['year'] = np.repeat(2018,sales_2018.shape[0])

sales = pd.concat([sales_2017,sales_2018], ignore_index=True)

sales


product  sales_units  year
0   chair           20  2017
1    sofa           24  2017
2   table           15  2017
3   chair           25  2018
4    sofa           10  2018
5   shelf           10  2018

In [108]:
# toss a coin
np.random.randint(2)
#1

# toss a coin 5 times
np.random.randint(2,size=5)
#array([1, 1, 0, 0, 0])

# roll a dice
np.random.randint(1,7)
#4

# roll a dice 10 times
np.random.randint(1,7,size=10)
#array([4, 6, 1, 6, 4, 4, 2, 3, 5, 2])

array([5, 5, 3, 3, 6, 3, 6, 6, 1, 4])

In [109]:

# toss a coin
np.random.choice([0,1])
#1

# toss a coin 5 times
np.random.choice([0,1],size=5)
#array([0, 1, 1, 1, 1])

# roll a dice
np.random.choice([1,2,3,4,5,6])
#3

# roll a dice 10 times
np.random.choice([1,2,3,4,5,6],size=10)
#array([3, 5, 6, 6, 6, 2, 5, 5, 1, 2])

array([4, 3, 3, 5, 6, 4, 6, 3, 6, 3])

In [110]:
houses_madrid.replace(['Unknown','-'],np.nan, inplace=True)

# check missing values
houses_madrid.isnull().sum()

NameError: name 'houses_madrid' is not defined

In [111]:
array = np.array([[1,2,3],[4,5,6]])

# index of maximum value
max_pos = np.argmax(array)

max_pos
#5

5

In [112]:
arr = np.array([[[1],[1]]])

arr.shape
#(1, 2, 1)

# squeeze out axis 0
arr0 = np.squeeze(arr,axis=0)
arr0
#array([[1],[1]])
arr0.shape
#(2, 1)

# squeeze out axis 1
arr1 = np.squeeze(arr,axis=1)
#ValueError - because the dimension of the axis 1 is not 1 but 2

# squeeze out axis 2
arr2 = np.squeeze(arr,axis=2)
arr2
#array([[1, 1]])
arr2.shape
#(1, 2)

# squeeze all axes of shape 1
arrall = np.squeeze(arr)
arrall
#array([1, 1])
arrall.shape
#(2,)

ValueError: cannot select an axis to squeeze out which has size not equal to one